<?php
/**
 * @file
 * Stack theme.
 *
 * Place your custom PHP code in this file.
 */


/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function thesaas_theme_suggestions_page_alter(array &$suggestions, array $variables) {

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $content_type = $node->bundle();
    if ($content_type == 'full_page' or $content_type == 'article' or $content_type == 'project' or $content_type == 'job') {
	  $suggestions[] = 'page__fullwidth';
	}
  }
  /*
  $view = \Drupal::service('entity.manager')->getStorage('view')->load('portfolio_wide');
  if ($view) {
    $suggestions[] = 'page__fullwidth';
  }
  if (($views_page = views_get_page_view()) && $views_page->name === "portfolio_wide") {
    $suggestions[] = 'page__fullwidth';
    }
  */
  $request = \Drupal::routeMatch()->getRouteObject()->getDefault('view_id');
  if (!empty($request) && $request == 'portfolio_wide' ) {
    $suggestions[] = 'page__fullwidth';
  }
}

/**
 * Add color, menu and theme settings
 */
function thesaas_preprocess_page(&$variables) {
  // Theme color
  $color = theme_get_setting('theme_color');
  if ($color != 'default') {
    $variables['#attached']['library'][] = 'thesaas/'.$color.'-styling';
  }

  // Theme menu
  $variables['mainmenu_class'] = '';

  $mainmenu_transparent_flag = 0;

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if ($node->hasField('field_menu_transparent')) {
	  //var_dump($node->get('field_menu_transparent')->getValue());
	  $mainmenu_transparent = $node->get('field_menu_transparent')->getValue();
	  if($mainmenu_transparent[0]['value']) {
        $mainmenu_transparent_flag = 1;
	  }
	}
	$node_type = \Drupal::entityTypeManager()->getStorage('node_type')->load($node->getType())->get('name');
	if($node_type == 'Project' ) {
            $mainmenu_transparent_flag = 1;
	}
	if($node_type == 'Job' ) {
            $mainmenu_transparent_flag = 1;
	}
	if($node_type == 'Article' ) {
	    $bg_img_url = $node->get('field_background_image')->getValue();
		if($bg_img_url[0]) {
          $mainmenu_transparent_flag = 1;
		}
	}
  }

  $menu = theme_get_setting('theme_menu');
  if( !$mainmenu_transparent_flag) {
    if( $menu == 'menudark') {
      $variables['mainmenu_class'] = 'bg--dark';
    }
    elseif( $menu == 'menulight') {
      $variables['mainmenu_class'] = 'bg--secondary';
    }
    else {
      $variables['mainmenu_class'] = 'navbar-dark';
    }
  }
  else {
    $variables['mainmenu_class'] = 'navbar-light';
  }


}

/**
 * Process block content
 */
function thesaas_theme_suggestions_block_alter(&$suggestions, $variables) {
  $content = $variables['elements']['content'];
  if (isset($content['#block_content']) && $content['#block_content'] instanceof \Drupal\block_content\BlockContentInterface) {
    $suggestions[] = 'block__' . $content['#block_content']->bundle();
  }

}

/**
 * Process block content
 */
function thesaas_preprocess_block(&$variables) {
  $variables['base_path'] = base_path();
}


/**
* Implements hook_form_alter() to add classes to the search form.
*/
function thesaas_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // disable submit button on the search block form
  if (in_array($form_id, ['search_block_form', 'search_form'])) {
    $key = ($form_id == 'search_block_form') ? 'actions' : 'basic';

    $form[$key]['submit']['#access'] = false;
  }
  if (strpos($form_id, 'simplenews_subscriptions') !== false) {
    //dpm($form);
    //$form['actions']['subscribe']['#submit'][] = 'thesaas_module_simplenews_subscribe';
    //$form['actions']['unsubscribe']['#submit'][] = 'thesaas_module_simplenews_unsubscribe';
  }
}

function thesaas_module_simplenews_subscribe(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    var_dump('we sent a form woohoo');
    //$url = \Drupal\Core\Url::fromUserInput('/page-thank-you');
    //$form_state->setRedirectUrl($url);
}
function thesaas_module_simplenews_unsubscribe(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    var_dump('we sent a form woohoo');
    //$url = \Drupal\Core\Url::fromUserInput('/page-thank-you');
    //$form_state->setRedirectUrl($url);
}

function thesaas_form_contact_message_book_en_demo_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Get the 'solution' query parameter from the URL
  $solution = \Drupal::request()->query->get('solution');

  // List of valid options for field_solution (adjust these values as per your configuration)
  $valid_values = ['digital_skiltning', 'formular', 'valg_og_bemanding', 'webplatforme', 'borgerinddragelse', 'moder_og_dagsorden'];  // Replace with your actual field options

  // If the 'solution' parameter is set and is a valid option
  if (!empty($solution) && in_array($solution, $valid_values)) {
    // Set the default value for the field_solution field
    $form['field_solution']['#default_value'] = $solution;
  }
  // If the solution parameter is not valid, we keep the current default value or let it be empty
}
